View(empdataset)
print(is.data.frame(empdataset))
print(ncol(empdataset))
print(nrow(empdataset))
sal<-max(empdataset$salary)
print(sal)
val<-subset(empdataset,dept=='Technical')
print(val)
val<-subset(empdataset,salary>950000 & dept=='Technical')
print(val)
mean(10,trim = 0,na.rm = FALSE)
median(10,na.rm = FALSE)
min(10)
max(10)
range(10)
summary(empdataset)
str(empdataset)
names(empdataset)
head(empdataset)
head(empdataset,n=8)
head(empdataset,n=-2)
tail(empdataset)
tail(empdataset,n=5)
tail(empdataset,n=-2)
empdataset[1:10,]
empdataset[1:10,1:3]
empdataset[,]
